# Generated by Django 4.1 on 2023-04-11 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ec13ce7-8caf-4253-9cc9-a6eee81f992f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
