# Generated by Django 4.1 on 2023-04-11 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('366e6c1c-ca84-4f95-8814-fa1191858370'), editable=False, primary_key=True, serialize=False),
        ),
    ]
