# Generated by Django 4.1 on 2023-04-14 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05c96756-46fd-4d04-a122-f693e2d885f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
