# Generated by Django 4.1 on 2023-04-14 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8a548d3-7ea9-49b6-9100-fc0c61611d40'), editable=False, primary_key=True, serialize=False),
        ),
    ]
