# Generated by Django 4.1 on 2023-04-16 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3ba6e23-8b30-4e9d-afaf-3b18b7a407a4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
